### ISSUE TITLE
Running example javascript-developer

### ISSUE THREAD

**Issue by vipersils** [lgrammel/gptagent.js#5]
I don't use pnpm for other projects ATM so not ![Screenshot from 2023-04-16 21-37-00](https://user-images.githubusercontent.com/88160672/232337868-73f45cb4-2b3e-43de-87f1-cac4ae6310e6.png)

This seems to be related to the docker build command and the architecture. PM coming right up to make the docs a bit more explicit but investigating a little further.

**Comment by lgrammel** [comment]
Yes - the docker build is for an m1 macbook (arm64). Ideally it would be multi-platform or choose the right platform.
